"""
Django settings for CarAccessories project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import djcelery

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@5**i(c=e_u$r!a=@(*oa!=7o_0j9*9y8wl(34uvsozv*9hgaa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CarNews',
    'CarPartsShop',
    'rest_framework',
    'djcelery'

]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'CarAccessories.middleware.RequestBlockingMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'CarAccessories.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CarAccessories.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '39.107.253.135',
            'PORT': '33060',
            'NAME': 'carparts',
            'USER': 'root',
            'PASSWORD': '7890',
            # 'HOST': '172.17.53.31',
        }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')

djcelery.setup_loader()
BOOKER_URL = 'redis://:127.0.0.1:6379/1'
CELERY_IMPORTS = ('CarPartsShop.task')
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7BqTy2T8YyIY6nMOy/L3Vx0Rib6sc/Zmzb2zys/HwERH0vnb3izKGasgf0TqoBu7jL3YoVNwY/N0Y/Ah1Qmmm+Tamd9uzWme/CZ5yl2D1sAPYbdv4gTFWoKYuzyhJDRnj5RbS48uPKoK5Rldum4ukZGhYEo5lPVm+pz9UQTA2uX+B3f7KCIYXwfNYzCEVJKv1XlTM536C0Y7jsIPZ4+5oVpin+UemO/PcOAZ0uWr9WWEDj+3aaKOp7l2dH0aCsN7iOWAU67WwUTOMnIg/q2/p0y0KN0SuAflRAjqg6ahCJqiwCorEIX+FbOdNQvGzKXowUDgWf8AO1r69pvtB4kYfwIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEA7BqTy2T8YyIY6nMOy/L3Vx0Rib6sc/Zmzb2zys/HwERH0vnb3izKGasgf0TqoBu7jL3YoVNwY/N0Y/Ah1Qmmm+Tamd9uzWme/CZ5yl2D1sAPYbdv4gTFWoKYuzyhJDRnj5RbS48uPKoK5Rldum4ukZGhYEo5lPVm+pz9UQTA2uX+B3f7KCIYXwfNYzCEVJKv1XlTM536C0Y7jsIPZ4+5oVpin+UemO/PcOAZ0uWr9WWEDj+3aaKOp7l2dH0aCsN7iOWAU67WwUTOMnIg/q2/p0y0KN0SuAflRAjqg6ahCJqiwCorEIX+FbOdNQvGzKXowUDgWf8AO1r69pvtB4kYfwIDAQABAoIBAQCvITenkwyy68PXg+jh1yModuNfbRO2IHs4+RG3yk+8ielM0REJx+dRCuJcBN6UTH3dc6SQZbfkK92Vk7VEtJfk4uhTYqxpqYLIPjHwrVTxohzGuq4+1JMfA+gOWnacyFJY6g6eCWKelPLn5NzlQH1CdOdi6Su1FiKAmpo70m7K7omuehNTcNOvCofgYrsw8hMqy54GDpuWK40B26TiRX9kgUde747gknbcGIzsk1IiK1CuqQMLYb7LpGxpaEOTpVQbfokW0aBrHgnYob+XpB//Pzg7xm931IS/qPWwjahvp+xh3udk3Zh2ggdSRorTZAbYYz9qVD7HP1mG04R/DURBAoGBAPmyZUdTtcfkcGlM4qVfpJhtyFck/0yhebOym+ZMsExVbIRK20av5b/HqXpk4+SzOmfYrTM6RTvyPx4yC54CtMpRnRzaLAe3xNnZ0AjZsGfCJ8w/+A8g5lnA+bH3idUMHpXGPw0DLjpIJvprSEtRjcRdxLXMKC5DNufM5t23cc9ZAoGBAPIQVwxQmVr9qmsLUNJ89acwQVuuqqIugZYtM+wnj/DbRXTWt/9M/Aj4UIxRa7hGCWQ9hqB5EOOAMCzrcTn+cnTMQoeNK9C35zASYmSvvqKtpITY9KCCyFUp97ScW1qb28+Vhw2aDNoBL+DNGmPF1o5Ham5E2f7BchLV4pWWT8OXAoGAPiQtnGCy3rp1V19xEGMLHXxE3ZsxhiqxlQ0gS2JOhdDEnu/aPm9MKDxSa0lsheAs6uc7w4H+9PpGxwcBaSOXRrqk9Sc+yfTsIqNYaLt0cX4aVXSeEXXInhGukqHeRY0sl22tB1oBSTPnr26/oS78rx/+8peKcGj94xZVZlxfEJECgYEArZMN+GSrMtYGp697ixPTyskNdMKw1I7omVlcjBBqZNm22mtFkSoQ6BW3HIcd6Qs/nMOJj/SAKcI3yV4i2OUeCaaWZkDSlF3qx0vHhk+HMXu2JxSzhY2CPZ9UYgxkbXqpiha8uwImCQUk4dvw+m5YxblsFhoE/2qTc/IvAfjAxY0CgYEAmCqhCqbTg+WWMaJO9R8LfuEQ2V5GEPCL8oVDqUlINGv+bknhxJZ57+kkUi4E5pQ5UVxEjTzSkSFRQDLbjJSePXBodFlbImTrbCIN1gLhJd22TtpSYCxb4jFeMCd32AUZJ5OuYjfGiZCUun9MBgvi9vlJ5Z/pe26u6deFC2OTdg8=
-----END RSA PRIVATE KEY-----"""
