# Generated by Django 2.1.8 on 2019-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarnewsCarnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=50, null=True)),
                ('news_time_str', models.CharField(blank=True, max_length=20, null=True)),
                ('news_art_time', models.CharField(blank=True, max_length=32, null=True)),
                ('news_list_img', models.CharField(blank=True, max_length=100, null=True)),
                ('news_path', models.CharField(blank=True, max_length=100, null=True)),
                ('news_read_num', models.CharField(blank=True, max_length=20, null=True)),
                ('news_comment_num', models.CharField(blank=True, max_length=20, null=True)),
                ('news_abstract', models.TextField(blank=True, null=True)),
                ('news_art_img', models.TextField(blank=True, null=True)),
                ('news_art_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CarNews_carnews',
                'managed': False,
            },
        ),
    ]
