# Generated by Django 2.1.8 on 2019-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=32)),
                ('age', models.IntegerField(default=100)),
            ],
        ),
    ]
