# Generated by Django 2.1.8 on 2019-10-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarNews', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
