# Generated by Django 2.1.8 on 2019-10-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('img', models.CharField(max_length=512, null=True)),
                ('price', models.CharField(max_length=32, null=True)),
                ('shops_num', models.IntegerField()),
                ('shops_total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationsCartUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userinfo_id', models.IntegerField()),
                ('cart_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
