# Generated by Django 2.1.8 on 2019-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnewsCarnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=50, null=True)),
                ('news_time_str', models.CharField(blank=True, max_length=20, null=True)),
                ('news_art_time', models.CharField(blank=True, max_length=32, null=True)),
                ('news_list_img', models.CharField(blank=True, max_length=100, null=True)),
                ('news_path', models.CharField(blank=True, max_length=100, null=True)),
                ('news_read_num', models.CharField(blank=True, max_length=20, null=True)),
                ('news_comment_num', models.CharField(blank=True, max_length=20, null=True)),
                ('news_abstract', models.TextField(blank=True, null=True)),
                ('news_art_img', models.TextField(blank=True, null=True)),
                ('news_art_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CarNews_carnews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarpartsshopCarparts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('img', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('grade', models.CharField(blank=True, max_length=32, null=True)),
                ('comment_number', models.CharField(blank=True, max_length=32, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('shop_feature', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'CarPartsShop_carparts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarpartsshopCartype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'CarPartsShop_cartype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_id', models.IntegerField()),
                ('od_shops_names', models.CharField(max_length=2048)),
                ('od_status', models.IntegerField()),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('od_shops_nums', models.IntegerField()),
                ('od_time', models.DateTimeField()),
                ('od_shops_total_price', models.IntegerField()),
            ],
        ),
    ]
