# Generated by Django 2.1.8 on 2019-10-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='1', max_length=128)),
                ('img', models.CharField(default='1', max_length=512)),
                ('price', models.CharField(default='1', max_length=32)),
                ('grade', models.CharField(default='1', max_length=32)),
                ('comment_number', models.CharField(default='1', max_length=32)),
                ('brand', models.CharField(default='1', max_length=32)),
                ('shop_feature', models.CharField(default='1', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='1', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='carparts',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CarPartsShop.CarType'),
        ),
    ]
