# Generated by Django 2.1.8 on 2019-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpartsClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
