# Generated by Django 2.1.8 on 2019-10-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsShop', '0002_carpartsclassify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarpartsClassify',
        ),
    ]
