# Generated by Django 2.1.8 on 2019-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsShop', '0002_carnewscarnews_carpartsshopcarparts_carpartsshopcartype_shopsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shops_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
